# Generated by Django 3.2.18 on 2023-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=1, verbose_name='추가 설명'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='problem',
            table='problem',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='solution',
        ),
    ]
