# Generated by Django 3.2.18 on 2023-05-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='display',
        ),
    ]
