# Generated by Django 3.2.18 on 2023-06-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
