# Generated by Django 3.2.18 on 2023-06-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230602_0022'),
        ('reviews', '0003_auto_20230602_0134'),
    ]

    operations = [
    ]
