# Generated by Django 3.2.18 on 2023-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230602_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='문제 링크'),
        ),
    ]
