# Generated by Django 3.2.18 on 2023-05-30 07:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], max_length=13),
        ),
        migrations.AddField(
            model_name='study',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
