# Generated by Django 3.2.18 on 2023-06-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='post_index',
            field=models.IntegerField(default=1, verbose_name='게시글 번호'),
        ),
    ]
