# Generated by Django 3.2.18 on 2023-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_announcement_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='join_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, '승인 필요'), (2, '바로 가입'), (3, '가입 불가')], default=1),
        ),
    ]
