# Generated by Django 3.2.18 on 2023-06-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_post_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='studies.study'),
        ),
    ]
