# Generated by Django 3.2.18 on 2023-05-31 00:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20230530_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], max_length=13),
        ),
    ]
