# Generated by Django 3.2.18 on 2023-05-31 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0003_alter_study_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('py', 'Python'), ('java', 'Java'), ('js', 'JavaScript'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('ruby', 'Ruby'), ('dart', 'Dart'), ('scala', 'Scala'), ('go', 'Golang'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('node_js', 'Node.js')], max_length=59),
        ),
        migrations.AlterField(
            model_name='studying',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_studyings', to='studies.study'),
        ),
        migrations.AlterField(
            model_name='studying',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_studyings', to=settings.AUTH_USER_MODEL),
        ),
    ]
