# Generated by Django 3.2.18 on 2023-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_study_join_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_recruiting',
            field=models.PositiveSmallIntegerField(choices=[(1, '모집 중'), (2, '모집 마감')], default=1),
        ),
    ]
