# Generated by Django 3.2.18 on 2023-05-31 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0004_auto_20230531_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='join_condition',
            field=models.CharField(choices=[(1, '승인 필요'), (2, '바로 가입')], default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='study',
            name='join_request',
            field=models.ManyToManyField(blank=True, related_name='study_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)]),
        ),
    ]
