# Generated by Django 3.2.18 on 2023-06-05 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0004_auto_20230605_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementread',
            name='studying',
        ),
        migrations.AddField(
            model_name='announcementread',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_read',
            field=models.ManyToManyField(related_name='user_read', through='studies.AnnouncementRead', to=settings.AUTH_USER_MODEL),
        ),
    ]
