# Generated by Django 3.2.18 on 2023-05-31 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0005_auto_20230531_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='studying_users',
            field=models.ManyToManyField(blank=True, related_name='user_studies', through='studies.Studying', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='join_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, '승인 필요'), (2, '바로 가입')], default=1, max_length=1),
        ),
    ]
