# Generated by Django 3.2.18 on 2023-06-05 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0005_auto_20230605_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_read',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_reads',
            field=models.ManyToManyField(related_name='user_reads', through='studies.AnnouncementRead', to=settings.AUTH_USER_MODEL),
        ),
    ]
