# Generated by Django 3.2.18 on 2023-06-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_is_recruiting'),
        ('studies', '0006_auto_20230606_0056'),
    ]

    operations = [
    ]
