# Generated by Django 3.2.18 on 2023-06-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_merge_20230607_0956'),
        ('studies', '0007_merge_20230607_1002'),
    ]

    operations = [
    ]
