# Generated by Django 3.2.18 on 2023-06-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_merge_20230607_1018'),
        ('studies', '0008_merge_20230607_1020'),
    ]

    operations = [
    ]
