# Generated by Django 3.2.18 on 2023-06-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20230607_1550'),
        ('studies', '0009_merge_20230607_1028'),
    ]

    operations = [
    ]
