# Generated by Django 3.2.18 on 2023-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_merge_20230608_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='studying',
            name='last_access_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
